import { ChartAreaInteractive } from "@/components/sidebar/chart-area-interactive";
import { DataTable } from "@/components/sidebar/data-table";
import { SectionCards } from "@/components/sidebar/section-cards";
import { SiteHeader } from "@/components/sidebar/site-header";
import { SidebarInset } from "@/components/ui/sidebar";

import data from "./data.json";
import { Suspense } from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard - Foxivo",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <SidebarInset>
        <SiteHeader siteName="Dashboard" />

        <div className="flex flex-1 flex-col">
          <div className="@container/main flex flex-1 flex-col gap-2">
            <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
              <SectionCards />
              <div className="px-4 lg:px-6">
                <ChartAreaInteractive />
              </div>
              <Suspense fallback="Loading...">
                <DataTable data={data} />
              </Suspense>
            </div>
          </div>
        </div>
      </SidebarInset>
    </>
  );
}
